Repository sodafoundation/api, pull requests merged in 2018-06, with the labels that each got.

#433 add metadata into the whitelist for replication api
  pkg/api/replication.go
Labels: patch

#435 Remove some keystone data which is not useful
  script/devsds/lib/keystone.sh
Labels: patch

#440 Fixed auth control
  dashboard/src/app/business/identity/tenantDetail/tenantDetail.component.ts
  dashboard/src/app/business/identity/userList.component.ts
Labels: patch

#438 Create volume from snapshot
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/lvm_test.go
  openapi-spec/swagger.yaml
  osdsctl/cli/volume.go
  pkg/api/db.go
  pkg/api/db_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/db/drivers/etcd/etcd_test.go
  pkg/dock/proto/dock.pb.go
  pkg/dock/proto/dock.proto
  pkg/model/volume.go
  testutils/collection/data.go
Labels: feature

#441 Fix some bugs and update integration test
  pkg/api/policy/policy.go
  pkg/api/policy/policy_test.go
  test/integration/client_test.go
  test/integration/controller_test.go
  testutils/db/fake.go
Labels: test

#446 resolve volume deletion error
  pkg/controller/controller.go
Labels: patch

#450 modify volume group info in swagger
  openapi-spec/swagger.yaml
Labels: document

#447 resolve profile error related to volume group.
  osdsctl/cli/volumegroup.go
  pkg/api/db.go
  pkg/api/volumeGroup.go
  pkg/controller/selector/selector.go
  pkg/model/volume.go
Labels: patch

#444 delete status deleted in status.go and modify related method in volume group.
  pkg/api/db.go
  pkg/controller/controller.go
  pkg/dock/dock.go
  pkg/model/status.go
Labels: patch

#452 Fixed some bugs about csi replication.
  contrib/drivers/replication_drivers.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/discovery/discovery.go
Labels: patch

#449 add filter to cli
  client/client.go
  client/dock.go
  client/pool.go
  client/profile.go
  client/replication.go
  client/volume.go
  client/volume_test.go
  osdsctl/cli/dock.go
  osdsctl/cli/pool.go
  osdsctl/cli/profile.go
  osdsctl/cli/replication.go
  osdsctl/cli/volume.go
  osdsctl/cli/volumeattachment.go
  osdsctl/cli/volumegroup.go
  osdsctl/cli/volumesnapshot.go
  pkg/controller/volume/volumecontroller.go
Labels: patch

#454 Check whether volume has snapshots before deleting the volume.
  pkg/api/db.go
  pkg/api/db_test.go
  pkg/api/volumeGroup.go
  pkg/controller/controller.go
Labels: patch

#455 Add Makefile in dashboard
  dashboard/Dockerfile
  dashboard/Makefile
  dashboard/image_builder.sh
Labels: enhancement, patch

#457 Dashboard add new feature
  dashboard/src/app/business/block/volume-detail/snapshot-list/snapshot-list.component.ts
  dashboard/src/app/business/block/volume-detail/volume-detail.component.html
  dashboard/src/app/business/block/volume-detail/volume-detail.component.ts
  dashboard/src/app/business/block/volume.service.ts
  dashboard/src/app/business/block/volumeGroup.component.ts
  dashboard/src/app/business/block/volumeGroup.html
  dashboard/src/app/business/block/volumeGroup.module.ts
  dashboard/src/app/business/block/volumeList.component.ts
  dashboard/src/app/business/block/volumeList.html
  dashboard/src/app/business/home/home.component.html
  dashboard/src/app/business/home/home.component.ts
  dashboard/src/app/business/home/imgItem.component/imgItem.component.html
  dashboard/src/app/business/home/imgItem.component/imgItem.component.scss
  dashboard/src/app/business/home/imgItem.component/imgItem.component.ts
  dashboard/src/app/business/identity/tenantDetail/tenantDetail.component.ts
  dashboard/src/app/business/profile/createProfile/createProfile.component.ts
  dashboard/src/app/business/profile/profileCard/profile-card.component.ts
  dashboard/src/app/business/profile/profileCard/suspension-frame/suspension-frame.component.ts
  dashboard/src/app/business/profile/storage-pools-table/storage-pools-table.component.html
  dashboard/src/app/business/profile/storage-pools-table/storage-pools-table.component.ts
  dashboard/src/app/components/datatable/datatable.scss
  dashboard/src/app/shared/utils/utils.ts
Labels: patch

#458 Fix some format errors
  Makefile
  client/client.go
  client/receiver.go
  contrib/connector/connector.go
  contrib/connector/fc/fc.go
  contrib/connector/fc/fibreChannel.go
  contrib/connector/fc/linuxfc.go
  contrib/connector/iscsi/iscsi.go
  contrib/connector/rbd/rbd.go
  contrib/drivers/drivers.go
  osdsctl/README.md
  osdsctl/cli/cli.go
  osdsctl/cli/common.go
  osdsctl/cli/table.go
  osdsctl/main.go
  pkg/api/base.go
  pkg/api/db.go
  pkg/api/policy/checks.go
  pkg/api/router.go
  pkg/context/context.go
  pkg/db/drivers/etcd/etcd.go
  pkg/model/pool.go
  pkg/model/profile.go
  pkg/model/status.go
  pkg/utils/constants/constants.go
  pkg/utils/urls/urls.go
Labels: patch

#436 Add e2e CI(root)
  script/CI/test
  test/e2e/e2ef_test.go
  test/e2e/path.go
  test/e2e/path.sh
  testutils/attach.go
  testutils/attach/connector.go
  testutils/attach/decode_hooks.go
  testutils/attach/error.go
  testutils/attach/helper.go
  testutils/attach/iscsi.go
  testutils/attach/mapstructure.go
  testutils/env/path.go
  testutils/env/path.sh
Labels: feature

#463 E2e improve
  script/CI/test
  test/e2e/connector/connector.go
  test/e2e/e2ef_test.go
  test/e2e/path.go
  test/e2e/path.sh
  testutils/attach.go
  testutils/attach/connector.go
  testutils/attach/decode_hooks.go
  testutils/attach/error.go
  testutils/attach/helper.go
  testutils/attach/iscsi.go
  testutils/attach/mapstructure.go
  testutils/env/path.go
  testutils/env/path.sh
Labels: patch

#462 Fixed keystone authentication failed issue
  pkg/api/filter/auth/keystone.go
  pkg/api/filter/context/context.go
  pkg/context/context.go
Labels: patch

#464 Fixed Dashboard
  dashboard/src/app/app-routing.module.ts
  dashboard/src/app/app.component.ts
  dashboard/src/app/business/block/block.component.ts
  dashboard/src/app/business/block/block.html
  dashboard/src/app/business/block/create-volume/create-volume.component.ts
  dashboard/src/app/business/block/create-volume/replication-group/replication-group.component.ts
  dashboard/src/app/business/block/volume-detail/replication-list/replication-list.component.html
  dashboard/src/app/business/block/volume-detail/replication-list/replication-list.component.ts
  dashboard/src/app/business/block/volume-group-detail/volume-group-detail.component.html
  dashboard/src/app/business/block/volume-group-detail/volume-group-detail.component.ts
  dashboard/src/app/business/block/volume-group-detail/volume-group-detail.module.ts
  dashboard/src/app/business/block/volume.service.ts
  dashboard/src/app/business/block/volumeGroup.component.ts
  dashboard/src/app/business/block/volumeGroup.html
  dashboard/src/app/business/block/volumeGroup.module.ts
  dashboard/src/app/business/block/volumeList.component.ts
  dashboard/src/app/business/block/volumeList.html
  dashboard/src/app/business/block/volumeList.module.ts
  dashboard/src/app/business/profile/createProfile/createProfile.component.html
  dashboard/src/app/business/profile/createProfile/createProfile.component.ts
  dashboard/src/app/business/profile/createProfile/createProfile.module.ts
  dashboard/src/app/business/profile/profileCard/profile-card.component.html
  dashboard/src/app/business/profile/profileCard/profile-card.component.ts
  dashboard/src/app/business/resource/storage/storage.component.ts
  dashboard/src/app/business/resource/storage/storage.html
  dashboard/src/app/i18n/en/keyID.json
  dashboard/src/app/i18n/zh/keyID.json
  dashboard/src/assets/business/css/site.scss
Labels: patch

#465 Fix some bugs
  client/auth.go
  client/client.go
  cmd/osdsdock/osdsdock.go
  contrib/cindercompatibleapi/api/router.go
  osdsctl/cli/cli.go
  pkg/utils/constants/constants.go
Labels: patch

#466 fix an error when delete volume
  pkg/api/db.go
Labels: patch

#468 Fixed some bugs about volume groups
  examples/policy.json
  osdsctl/completion/osdsctl.bash_completion
  pkg/api/volumeGroup.go
Labels: patch

#470 Fixed dashboard volume list display bug
  dashboard/src/app/business/block/volumeList.component.ts
  dashboard/src/app/business/block/volumeList.html
Labels: patch

#475 Set the build as the default target in Makefile
  .travis.yml
  Makefile
Labels: patch

#473 Add volume attachment check before deleting volume
  pkg/api/db.go
  pkg/api/db_test.go
  test/integration/client_test.go
  testutils/db/fake.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/schedulerstats/results.go
Labels: patch

#477 Add Aruba POC Test Plan
  docs/test-plans/OpenSDS_Aruba_POC_Plan_v0.3.pdf
Labels: document

#479 Fixed dorado lunGroup paramter failed error
  contrib/drivers/huawei/dorado/client.go
  contrib/drivers/huawei/dorado/common.go
Labels: patch

#480 Dashboard fixed bugs
  dashboard/src/app/app.component.html
  dashboard/src/app/app.component.ts
  dashboard/src/app/business/block/create-volume/create-volume.component.ts
  dashboard/src/app/business/block/create-volume/replication-group/replication-group.component.html
  dashboard/src/app/business/block/create-volume/replication-group/replication-group.component.ts
  dashboard/src/app/business/block/volume-detail/replication-list/replication-list.component.html
  dashboard/src/app/business/block/volume-detail/replication-list/replication-list.component.ts
  dashboard/src/app/business/block/volume-detail/snapshot-list/snapshot-list.component.html
  dashboard/src/app/business/block/volume-detail/volume-detail.component.html
  dashboard/src/app/business/block/volume-group-detail/volume-group-detail.component.html
  dashboard/src/app/business/block/volume.service.ts
  dashboard/src/app/business/block/volumeGroup.html
  dashboard/src/app/business/block/volumeList.component.ts
  dashboard/src/app/business/block/volumeList.html
  dashboard/src/app/business/identity/tenantList.html
  dashboard/src/app/business/identity/userList.component.ts
  dashboard/src/app/business/identity/userList.html
  dashboard/src/app/i18n/en/keyID.json
  dashboard/src/app/i18n/zh/keyID.json
  dashboard/src/app/shared/service/ParamStor.service.ts
Labels: patch

#482 Merge development into master branch for publishing v0.2.0 release
  Makefile
  contrib/drivers/huawei/dorado/client.go
  contrib/drivers/huawei/dorado/common.go
  dashboard/src/app/app.component.html
  dashboard/src/app/app.component.ts
  dashboard/src/app/business/block/create-volume/create-volume.component.ts
  dashboard/src/app/business/block/create-volume/replication-group/replication-group.component.html
  dashboard/src/app/business/block/create-volume/replication-group/replication-group.component.ts
  dashboard/src/app/business/block/volume-detail/replication-list/replication-list.component.html
  dashboard/src/app/business/block/volume-detail/replication-list/replication-list.component.ts
  dashboard/src/app/business/block/volume-detail/snapshot-list/snapshot-list.component.html
  dashboard/src/app/business/block/volume-detail/volume-detail.component.html
  dashboard/src/app/business/block/volume-group-detail/volume-group-detail.component.html
  dashboard/src/app/business/block/volume.service.ts
  dashboard/src/app/business/block/volumeGroup.html
  dashboard/src/app/business/block/volumeList.component.ts
  dashboard/src/app/business/block/volumeList.html
  dashboard/src/app/business/identity/tenantList.html
  dashboard/src/app/business/identity/userList.component.ts
  dashboard/src/app/business/identity/userList.html
  dashboard/src/app/i18n/en/keyID.json
  dashboard/src/app/i18n/zh/keyID.json
  dashboard/src/app/shared/service/ParamStor.service.ts
Labels: release

#483 Add OpenSDS Aruba POC Plan v0.4 and v0.5
  docs/test-plans/OpenSDS_Aruba_POC_Plan_v0.4.pdf
  docs/test-plans/OpenSDS_Aruba_POC_Plan_v0.5.pdf
Labels: document
