Repository sodafoundation/api, pull requests merged in 2018-04, with the labels that each got.

#334 Merge development into master branch for publishing v0.1.6 release
  client/pool_test.go
  client/profile_test.go
  cmd/osdsdock/osdsdock.go
  contrib/ansible/group_vars/ceph/ceph.yaml
  contrib/ansible/group_vars/cinder/cinder.yaml
  contrib/ansible/group_vars/lvm/lvm.yaml
  contrib/drivers/ceph/ceph.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/dorado/testdata/dorado.yaml
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/lvm_test.go
  contrib/drivers/lvm/testdata/lvm.yaml
  contrib/drivers/openstack/cinder/cinder.go
  contrib/drivers/utils/config/config.go
  contrib/drivers/utils/config/config_test.go
  contrib/drivers/utils/config/testdata/config.yaml
  docs/readthedocs/contributing/Community-Contributing.md
  docs/readthedocs/contributing/Tutorials-for-Beginners.md
  docs/readthedocs/installation/How-to-Run-Containerized-OpenSDS-for-Testing-Work.md
  docs/readthedocs/installation/Local-Cluster-Installation-through-Ansible.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-Ceph.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-Cinder-Standalone.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-LVM.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-CSI.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-Flexvolume.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-Service-Catalog.md
  examples/driver/ceph.yaml
  examples/driver/cinder.yaml
  examples/driver/lvm.yaml
  osdsctl/cli/volumeattachment.go
  pkg/api/db.go
  pkg/api/db_test.go
  pkg/api/filter/auth/auth.go
  pkg/api/pool_test.go
  pkg/api/volume.go
  pkg/api/volume_test.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/policy/policycontroller.go
  pkg/controller/selector/filter_test.go.old
  pkg/controller/selector/selector_test.go.old
  pkg/controller/volume/volumecontroller.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/db/drivers/etcd/etcd_test.go
  pkg/dock/dock.go
  pkg/dock/server/server.go
  pkg/model/base.go
  pkg/model/pool.go
  pkg/model/profile.go
  pkg/model/volume.go
  pkg/utils/utils_test.go.old
  testutils/collection/data.go
  testutils/db/testing/mock_db.go
Labels: release

#335 Add iscsi and rbd connector
  contrib/connector/connector.go
  contrib/connector/iscsi/helper.go
  contrib/connector/iscsi/iscsi.go
  contrib/connector/rbd/rbd.go
  glide.lock
  glide.yaml
  vendor/github.com/coreos/etcd/Documentation/upgrades/upgrade_3_0.md
  vendor/github.com/coreos/etcd/Documentation/upgrades/upgrade_3_1.md
  vendor/github.com/coreos/etcd/Documentation/upgrades/upgrade_3_2.md
  vendor/github.com/coreos/etcd/Documentation/upgrades/upgrade_3_3.md
  vendor/github.com/coreos/etcd/Documentation/upgrades/upgrade_3_4.md
  vendor/github.com/coreos/etcd/compactor/compactor.go
  vendor/github.com/coreos/etcd/compactor/periodic.go
  vendor/github.com/coreos/etcd/compactor/periodic_test.go
  vendor/github.com/coreos/etcd/compactor/revision.go
  vendor/github.com/coreos/etcd/compactor/revision_test.go
  vendor/github.com/coreos/etcd/etcdserver/raft.go
  vendor/github.com/coreos/etcd/etcdserver/server.go
  vendor/github.com/coreos/etcd/etcdserver/util_test.go
  vendor/github.com/coreos/etcd/rafthttp/peer.go
  vendor/github.com/coreos/etcd/rafthttp/remote.go
  vendor/github.com/coreos/etcd/rafthttp/transport.go
  vendor/github.com/coreos/etcd/version/version.go
  vendor/github.com/mitchellh/mapstructure/.travis.yml
  vendor/github.com/mitchellh/mapstructure/LICENSE
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/decode_hooks_test.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
  vendor/github.com/mitchellh/mapstructure/mapstructure_benchmark_test.go
  vendor/github.com/mitchellh/mapstructure/mapstructure_bugs_test.go
  vendor/github.com/mitchellh/mapstructure/mapstructure_examples_test.go
  vendor/github.com/mitchellh/mapstructure/mapstructure_test.go
Labels: enhancement

#337 Remove unnecessary field in proto
  pkg/controller/controller.go
  pkg/dock/proto/dock.pb.go
  pkg/dock/proto/dock.proto
Labels: bug

#338 Fixed some bugs about etcd db object update authentication.
  pkg/db/drivers/etcd/etcd.go
Labels: bug

#341 Fixed a CI unit test bug
  pkg/utils/utils_test.go
Labels: bug

#340 Add attach dock server for attaching and detaching operation
  pkg/controller/volume/volumecontroller_test.go
  pkg/dock/client/client.go
  pkg/dock/dock.go
  pkg/dock/proto/dock.pb.go
  pkg/dock/proto/dock.proto
  pkg/dock/server/server.go
Labels: enhancement

#343 Update opensds helm charts
  charts/opensds/templates/deployment.yaml
  charts/opensds/templates/service.yaml
  charts/opensds/values.yaml
Labels: bug

#348 Since the StoragePoolSpec has changed, modify the selector
  pkg/controller/selector/filter.go
  pkg/controller/selector/filter_test.go
  pkg/controller/selector/filter_test.go.old
  pkg/controller/selector/selector_test.go
Labels: bug, enhancement

#350 Update e2e test
  test/e2e/e2e_test.go
Labels: enhancement

#351 Fix a bug in attach dock
  pkg/dock/dock.go
Labels: patch

#353 Decouple attach dock and provision dock
  client/receiver.go
  cmd/osdsdock/osdsdock.go
  examples/opensds.conf
  pkg/dock/discovery/discovery.go
  pkg/dock/discovery/discovery_test.go
  pkg/dock/dock.go
  pkg/model/dock.go
  pkg/utils/config/config_define.go
Labels: patch

#352 Fixed some bugs about dorado
  contrib/drivers/huawei/dorado/client.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/dorado/utils.go
  contrib/drivers/huawei/dorado/utils_test.go
Labels: patch

#355 Update mailing list and meeting info
  COMMUNITY.md
  CONTRIBUTING.md
  README.md
Labels: document

#357 Remove -f option from lvm volume deletion.
  contrib/drivers/lvm/lvm.go
Labels: patch

#359 Refatored the LVM ISCSI feature.
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/lvm_test.go
  contrib/drivers/lvm/targets/iscsi.go
  contrib/drivers/lvm/targets/targets.go
  contrib/drivers/lvm/testdata/lvm.yaml
Labels: enhancement

#362 Fixed some bugs
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/targets/iscsi.go
  osdsctl/cli/profile.go
  osdsctl/cli/table.go
  osdsctl/cli/volume.go
  osdsctl/cli/volumeattachment.go
  osdsctl/cli/volumeattachment_test.go
  osdsctl/cli/volumesnapshot.go
  pkg/api/db.go
Labels: patch

#367 Fix some bugs
  contrib/drivers/lvm/lvm.go
  pkg/api/db.go
Labels: patch

#370 Fix some bugs
  cmd/osdsdock/Dockerfile
  contrib/drivers/lvm/lvm.go
Labels: patch
