Repository sodafoundation/api, pull requests merged in 2018-03, with the labels that each got.

#289 Add keystone feature
  pkg/api/filter/auth/auth.go
  pkg/api/filter/auth/keystone.go
  pkg/api/policy/checks.go
  pkg/api/policy/checks_test.go
  pkg/api/policy/parser.go
  pkg/api/policy/parser_test.go
  pkg/api/policy/policy.go
  pkg/api/policy/policy_test.go
  pkg/api/policy/testdata/policy.json
  pkg/api/policy/testdata/token.json
  pkg/api/router.go
  pkg/context/context.go
  pkg/context/context_test.go
  pkg/model/error.go
  pkg/utils/config/config_define.go
Labels: feature

#281 Add capability report loop support
  contrib/drivers/ceph/ceph.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/dorado/testdata/dorado.yaml
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/lvm_test.go
  contrib/drivers/lvm/testdata/lvm.yaml
  contrib/drivers/openstack/cinder/cinder.go
  contrib/drivers/utils/config/config.go
  contrib/drivers/utils/config/config_test.go
  contrib/drivers/utils/config/testdata/config.yaml
  examples/driver/lvm.yaml
  pkg/dock/discovery/discovery.go
  pkg/dock/discovery/discovery_test.go
  pkg/dock/dock.go
Labels: feature

#296 optimize client receiver
  client/dock.go
  client/dock_test.go
  client/pool.go
  client/pool_test.go
  client/profile.go
  client/profile_test.go
  client/receiver.go
  client/version.go
  client/version_test.go
  client/volume.go
  client/volume_test.go
  osdsctl/cli/cli_test.go
Labels: enhancement

#299 modify opensds docs
  docs/readthedocs/community/euac.md
  docs/readthedocs/community/tsc.md
  docs/readthedocs/contributing/Community-Contributing.md
  docs/readthedocs/contributing/Tutorials-for-Beginners.md
  docs/readthedocs/index.rst
  docs/readthedocs/installation/How-to-Run-Containerized-OpenSDS-for-Testing-Work.md
  docs/readthedocs/installation/Local-Cluster-Installation-through-Ansible.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-Ceph.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-Cinder-Standalone.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-LVM.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-CSI.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-Flexvolume.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-Service-Catalog.md
  docs/readthedocs/introduction/design-specs.md
  docs/readthedocs/introduction/nbp.md
  docs/readthedocs/introduction/opensds.md
Labels: patch

#301 Add nbp installation steps in opensds ansible script
  contrib/ansible/README.md
  contrib/ansible/clean.yml
  contrib/ansible/group_vars/ceph/all.yml
  contrib/ansible/group_vars/ceph/ceph.hosts
  contrib/ansible/group_vars/ceph/ceph.yaml
  contrib/ansible/group_vars/ceph/osds.yml
  contrib/ansible/group_vars/common.yml
  contrib/ansible/group_vars/lvm/lvm.yaml
  contrib/ansible/group_vars/osdsdb.yml
  contrib/ansible/group_vars/osdsdock.yml
  contrib/ansible/group_vars/osdslet.yml
  contrib/ansible/install_ansible.sh
  contrib/ansible/local.hosts
  contrib/ansible/roles/cleaner/tasks/main.yml
  contrib/ansible/roles/common/tasks/main.yml
  contrib/ansible/roles/nbp-installer/scenarios/csi.yml
  contrib/ansible/roles/nbp-installer/scenarios/flexvolume.yml
  contrib/ansible/roles/nbp-installer/tasks/main.yml
  contrib/ansible/roles/osdsdb/scenarios/container.yml
  contrib/ansible/roles/osdsdb/scenarios/etcd.yml
  contrib/ansible/roles/osdsdb/tasks/main.yml
  contrib/ansible/roles/osdsdock/scenarios/ceph.yml
  contrib/ansible/roles/osdsdock/scenarios/cinder.yml
  contrib/ansible/roles/osdsdock/scenarios/lvm.yml
  contrib/ansible/roles/osdsdock/tasks/main.yml
  contrib/ansible/roles/osdslet/tasks/main.yml
  contrib/ansible/site.yml
Labels: enhancement

#302 Add license declaration in opensds ansible script
  contrib/ansible/clean.yml
  contrib/ansible/group_vars/ceph/all.yml
  contrib/ansible/group_vars/ceph/ceph.hosts
  contrib/ansible/group_vars/ceph/ceph.yaml
  contrib/ansible/group_vars/ceph/osds.yml
  contrib/ansible/group_vars/cinder/cinder.yaml
  contrib/ansible/group_vars/common.yml
  contrib/ansible/group_vars/lvm/lvm.yaml
  contrib/ansible/group_vars/osdsdb.yml
  contrib/ansible/group_vars/osdsdock.yml
  contrib/ansible/group_vars/osdslet.yml
  contrib/ansible/local.hosts
  contrib/ansible/roles/cleaner/tasks/main.yml
  contrib/ansible/roles/common/tasks/main.yml
  contrib/ansible/roles/nbp-installer/scenarios/csi.yml
  contrib/ansible/roles/nbp-installer/scenarios/flexvolume.yml
  contrib/ansible/roles/nbp-installer/tasks/main.yml
  contrib/ansible/roles/osdsdb/scenarios/container.yml
  contrib/ansible/roles/osdsdb/scenarios/etcd.yml
  contrib/ansible/roles/osdsdb/tasks/main.yml
  contrib/ansible/roles/osdsdock/scenarios/ceph.yml
  contrib/ansible/roles/osdsdock/scenarios/cinder.yml
  contrib/ansible/roles/osdsdock/scenarios/cinder_standalone.yml
  contrib/ansible/roles/osdsdock/scenarios/lvm.yml
  contrib/ansible/roles/osdsdock/tasks/main.yml
  contrib/ansible/roles/osdslet/tasks/main.yml
  contrib/ansible/site.yml
Labels: patch

#303 Enable multiple pools of ceph backend in ansible script and update th…
  contrib/ansible/README.md
  contrib/ansible/group_vars/ceph/ceph.yaml
  contrib/ansible/group_vars/cinder/cinder.yaml
  contrib/ansible/group_vars/common.yml
  contrib/ansible/group_vars/lvm/lvm.yaml
  contrib/ansible/group_vars/osdsdb.yml
  contrib/ansible/group_vars/osdsdock.yml
  contrib/ansible/group_vars/osdslet.yml
  contrib/ansible/roles/cleaner/tasks/main.yml
  contrib/ansible/roles/common/tasks/main.yml
  contrib/ansible/roles/osdsdock/scenarios/ceph.yml
  contrib/ansible/roles/osdsdock/scenarios/lvm.yml
Labels: patch

#306 datafilt
  pkg/api/base.go
  pkg/api/dock.go
  pkg/api/dock_test.go
  pkg/api/pool.go
  pkg/api/pool_test.go
  pkg/api/profile.go
  pkg/api/profile_test.go
  pkg/api/volume.go
  pkg/api/volume_test.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/db/drivers/etcd/etcd_test.go
  testutils/collection/data.go
  testutils/db/fake.go
  testutils/db/testing/mock_db.go
Labels: feature

#309 replace project id with tenant id
  osdsctl/cli/volumeattachment.go
  pkg/api/filter/auth/keystone.go
  pkg/context/context.go
  pkg/db/drivers/etcd/etcd.go
  pkg/model/pool.go
  pkg/model/volume.go
Labels: patch

#297 scheduler echancement
  pkg/controller/controller.go
  pkg/controller/selector/filter.go
  pkg/controller/selector/filter_test.go
  pkg/controller/selector/selector.go
  pkg/controller/selector/selector_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: feature

#313 Merge development to master branch so as to publish next release
  contrib/ansible/README.md
  contrib/ansible/group_vars/common.yml
  contrib/ansible/group_vars/lvm/lvm.yaml
  contrib/ansible/roles/osdsdb/scenarios/etcd.yml
  docs/readthedocs/contributing/Community-Contributing.md
  docs/readthedocs/installation/Local-Cluster-Installation-through-Ansible.md
  glide.lock
  glide.yaml
  pkg/api/glide.lock
  script/devsds/lib/etcd.sh
  vendor/Third Party Open Source Software Notice.docx
  vendor/github.com/coreos/etcd/.semaphore.sh
  vendor/github.com/coreos/etcd/.travis.yml
  vendor/github.com/coreos/etcd/Documentation/learning/why.md
  vendor/github.com/coreos/etcd/Documentation/op-guide/maintenance.md
  vendor/github.com/coreos/etcd/clientv3/integration/lease_test.go
  vendor/github.com/coreos/etcd/clientv3/options.go
  vendor/github.com/coreos/etcd/e2e/util.go
  vendor/github.com/coreos/etcd/e2e/v3_curl_test.go
  vendor/github.com/coreos/etcd/embed/config.go
  vendor/github.com/coreos/etcd/embed/config_test.go
  vendor/github.com/coreos/etcd/embed/etcd.go
  vendor/github.com/coreos/etcd/etcdctl/README.md
  vendor/github.com/coreos/etcd/etcdserver/api/v3election/election.go
  vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes/error.go
  vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/util.go
  vendor/github.com/coreos/etcd/etcdserver/raft.go
  vendor/github.com/coreos/etcd/hack/scripts-dev/Makefile
  vendor/github.com/coreos/etcd/hack/scripts-dev/docker-dns/certs/run.sh
  vendor/github.com/coreos/etcd/hack/scripts-dev/docker-dns/insecure/Procfile
  vendor/github.com/coreos/etcd/hack/scripts-dev/docker-dns/insecure/run.sh
  vendor/github.com/coreos/etcd/lease/lessor.go
  vendor/github.com/coreos/etcd/lease/lessor_test.go
  vendor/github.com/coreos/etcd/proxy/httpproxy/reverse.go
  vendor/github.com/coreos/etcd/version/version.go
  vendor/github.com/go-ini/ini/.travis.yml
  vendor/github.com/go-ini/ini/Makefile
  vendor/github.com/go-ini/ini/README.md
  vendor/github.com/go-ini/ini/README_ZH.md
  vendor/github.com/go-ini/ini/file.go
  vendor/github.com/go-ini/ini/file_test.go
  vendor/github.com/go-ini/ini/ini.go
  vendor/github.com/go-ini/ini/ini_test.go
  vendor/github.com/go-ini/ini/struct_test.go
  vendor/github.com/go-ini/ini/testdata/TestFile_WriteTo.golden
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/assertions_test.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/github.com/stretchr/testify/mock/mock_test.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
Labels: release

#315 Optimize the function of converting StoragePoolSpec to map
  pkg/controller/selector/filter.go
  pkg/controller/selector/filter_test.go
  pkg/controller/selector/selector_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: enhancement

#318 Fix a bug in lvm backend and enable attachment test cases in e2e test
  contrib/drivers/lvm/targets/targets.go
  test/e2e/e2e_test.go
Labels: bug, patch

#319 Merge development to master branch so as to publish v0.1.5 release
  client/receiver.go
  contrib/drivers/lvm/targets/targets.go
  osdsctl/cli/cli.go
  osdsctl/cli/common.go
  osdsctl/cli/dock.go
  osdsctl/cli/pool.go
  osdsctl/cli/profile.go
  osdsctl/cli/table.go
  osdsctl/cli/version.go
  osdsctl/cli/volume.go
  osdsctl/cli/volumeattachment.go
  osdsctl/cli/volumesnapshot.go
  pkg/api/glide.lock
  pkg/api/pool.go
  pkg/api/profile.go
  pkg/api/volume.go
  pkg/controller/selector/filter.go
  pkg/controller/selector/filter_test.go
  pkg/controller/selector/selector_test.go
  pkg/db/drivers/etcd/etcd.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/e2e/e2e_test.go
Labels: release

#322 Fixed some bugs about ceph driver
  contrib/drivers/ceph/ceph.go
  pkg/context/context.go
Labels: patch

#325 When extending a volume, check the upper limit of the new size of the…
  pkg/api/volume.go
  pkg/api/volume_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: patch

#311 Capabilities properties design of storage pool
  client/pool_test.go
  client/profile_test.go
  contrib/ansible/group_vars/ceph/ceph.yaml
  contrib/ansible/group_vars/cinder/cinder.yaml
  contrib/ansible/group_vars/lvm/lvm.yaml
  contrib/drivers/ceph/ceph.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/dorado/testdata/dorado.yaml
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/lvm_test.go
  contrib/drivers/lvm/testdata/lvm.yaml
  contrib/drivers/openstack/cinder/cinder.go
  contrib/drivers/utils/config/config.go
  contrib/drivers/utils/config/config_test.go
  contrib/drivers/utils/config/testdata/config.yaml
  examples/driver/ceph.yaml
  examples/driver/cinder.yaml
  examples/driver/lvm.yaml
  pkg/api/pool_test.go
  pkg/controller/selector/filter_test.go.old
  pkg/controller/selector/selector_test.go.old
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd_test.go
  pkg/model/base.go
  pkg/model/pool.go
  pkg/model/profile.go
  pkg/utils/utils_test.go.old
  testutils/collection/data.go
Labels: feature

#330 [WIP] add replication feature
  contrib/drivers/drbd/replication.go
  contrib/drivers/replication_drivers.go
  examples/policy.json
  pkg/api/base.go
  pkg/api/dock_test.go
  pkg/api/filter/auth/auth.go
  pkg/api/pool_test.go
  pkg/api/profile_test.go
  pkg/api/replication.go
  pkg/api/router.go
  pkg/api/version_test.go
  pkg/api/volume_test.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/selector/selector_test.go
  pkg/controller/volume/volumecontroller.go
  pkg/controller/volume/volumecontroller_test.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/db/drivers/etcd/etcd_test.go
  pkg/dock/discovery/discovery_test.go
  pkg/dock/dock.go
  pkg/dock/proto/dock.pb.go
  pkg/dock/proto/dock.proto
  pkg/dock/server/server.go
  pkg/model/replication.go
  pkg/utils/urls/urls.go
  testutils/collection/data.go
  testutils/db/fake.go
  testutils/db/testing/mock_db.go
  testutils/driver/replication_sample.go
Labels: feature

#326 volume, snapshot, attachment statemachine and synchronous to asynchronous
  contrib/drivers/ceph/ceph.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/lvm/lvm.go
  contrib/drivers/openstack/cinder/cinder.go
  osdsctl/cli/volumeattachment.go
  pkg/api/db.go
  pkg/api/db_test.go
  pkg/api/volume.go
  pkg/api/volume_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/policy/policycontroller.go
  pkg/controller/volume/volumecontroller.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/dock.go
  pkg/model/volume.go
  testutils/db/testing/mock_db.go
Labels: feature

#333 update dock server
  cmd/osdsdock/osdsdock.go
  pkg/dock/server/server.go
Labels: enhancement
