Repository sodafoundation/api, pull requests merged in 2018-11, with the labels that each got.

#538 Add huawei fusionstorage driver
  contrib/drivers/drivers.go
  contrib/drivers/huawei/fusionstorage/cli.go
  contrib/drivers/huawei/fusionstorage/fusionstorage.go
  contrib/drivers/huawei/fusionstorage/fusionstorage_test.go
  contrib/drivers/huawei/fusionstorage/model.go
  contrib/drivers/huawei/fusionstorage/parser.go
  contrib/drivers/huawei/fusionstorage/testdata/fusionstorage.yaml
  contrib/drivers/utils/config/constants.go
  examples/driver/fusionstorage.yaml
  examples/opensds.conf
  pkg/utils/config/config_define.go
  pkg/utils/exec/exec.go
Labels: feature

#539 add profile for snapshot
  openapi-spec/swagger.yaml
Labels: document

#540 Cindercompatibleapi does not authenticate when "List Api Versions"
  contrib/cindercompatibleapi/api/router.go
Labels: patch

#544 Fixed get fs parsing bug
  contrib/connector/iscsi/helper.go
Labels: patch

#545 Add deleting uploaded snapshot
  contrib/backup/multicloud/client.go
  contrib/backup/multicloud/driver.go
Labels: patch

#541 Refactor connector framework
  contrib/connector/common.go
  contrib/connector/connector.go
  contrib/connector/fc/fc.go
  contrib/connector/fc/fibreChannel.go
  contrib/connector/iscsi/helper.go
  contrib/connector/iscsi/iscsi.go
  contrib/connector/rbd/rbd.go
  contrib/drivers/huawei/dorado/dorado.go
  pkg/dock/discovery/discovery.go
Labels: enhancement

#549 dorado: create volume from snapshot
  contrib/drivers/huawei/dorado/dorado.go
Labels: patch

#552 make log flushing shorter, and fixed some flag bugs
  cmd/osdsdock/osdsdock.go
  cmd/osdslet/osdslet.go
  pkg/api/filter/accesslog/accesslog.go
  pkg/api/router.go
  pkg/utils/config/config_define.go
  pkg/utils/config/flag.go
  pkg/utils/logs/logs.go
Labels: patch

#557 update go version from go1.9.2 to go1.11.1
  script/devsds/bootstrap.sh
Labels: patch

#559 Delete \r and \n in the result of GetFSType
  contrib/connector/common.go
Labels: patch
