Repository sodafoundation/api, pull requests merged in 2018-08, with the labels that each got.

#507 Dashboard fix bugs for Availability Zones
  dashboard/src/app/business/block/create-volume/create-volume.component.html
  dashboard/src/app/business/block/create-volume/create-volume.component.ts
  dashboard/src/app/business/block/volume-detail/snapshot-list/snapshot-list.component.ts
  dashboard/src/app/business/block/volumeGroup.html
  dashboard/src/app/shared/utils/utils.ts
Labels: patch

#511 Add test cases for volume group operation in e2e test
  test/e2e/e2e_test.go
Labels: test

#497 Adds an API to return Availability Zones for pools
  examples/policy.json
  openapi-spec/swagger.yaml
  pkg/api/pool.go
  pkg/api/pool_test.go
  pkg/api/router.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/db/drivers/etcd/etcd_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  testutils/db/fake.go
  testutils/db/testing/mock_db.go
Labels: patch

#513 Merge development into master branch for publishing Bali milestone-1
  examples/policy.json
  openapi-spec/swagger.yaml
  pkg/api/pool.go
  pkg/api/pool_test.go
  pkg/api/router.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/db/drivers/etcd/etcd_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  testutils/db/fake.go
  testutils/db/testing/mock_db.go
Labels: release

#509 TestVolumeActionInitializeConnectionWithError in contrib/cindercompaibleapi/api/volume_test.go should modify sleep call
  contrib/cindercompatibleapi/api/volume.go
  contrib/cindercompatibleapi/api/volume_test.go
Labels: patch
