Repository sodafoundation/api, pull requests merged in 2018-05, with the labels that each got.

#372 Fix some erros in e2e test
  pkg/db/drivers/etcd/etcd_test.go
  test/e2e/e2e_test.go
  test/integration/client_test.go
  test/integration/prepare.sh
  testutils/collection/data.go
Labels: enhancement

#371 Remove cluster folder and move bootstrap script to devsds
  charts/opensds/Chart.yaml
  charts/opensds/templates/_helpers.tpl
  charts/opensds/templates/deployment.yaml
  charts/opensds/templates/service.yaml
  charts/opensds/values.yaml
  script/devsds/bootstrap.sh
Labels: patch

#369 Volume group for swagger
  openapi-spec/swagger.yaml
Labels: enhancement

#368 volume group related operations, such as delete, create, show, list.
  client/volume.go
  client/volume_test.go
  contrib/drivers/ceph/ceph.go
  contrib/drivers/drivers.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/lvm/lvm.go
  contrib/drivers/openstack/cinder/cinder.go
  osdsctl/cli/cli_test.go
  osdsctl/cli/profile.go
  osdsctl/cli/volume.go
  osdsctl/cli/volumegroup.go
  osdsctl/cli/volumegroup_test.go
  pkg/api/base.go
  pkg/api/db.go
  pkg/api/router.go
  pkg/api/volumeGroup.go
  pkg/api/volumeGroup_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/selector/selector.go
  pkg/controller/volume/volumecontroller.go
  pkg/controller/volume/volumecontroller_test.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/dock.go
  pkg/dock/proto/dock.pb.go
  pkg/dock/proto/dock.proto
  pkg/dock/server/server.go
  pkg/model/error.go
  pkg/model/status.go
  pkg/model/volume.go
  pkg/utils/urls/urls.go
  testutils/collection/data.go
  testutils/db/fake.go
  testutils/db/testing/mock_db.go
  testutils/driver/sample.go
Labels: feature

#376 Change the method of replication action from 'PUT' TO 'POST'
  client/replication.go
  pkg/api/router.go
Labels: patch

#378 Add osdsctl replication ci and opmtimze some code
  osdsctl/cli/cli_test.go
  osdsctl/cli/dock_test.go
  osdsctl/cli/pool_test.go
  osdsctl/cli/profile_test.go
  osdsctl/cli/replication_test.go
  osdsctl/cli/version_test.go
  osdsctl/cli/volume_test.go
  osdsctl/cli/volumeattachment_test.go
  osdsctl/cli/volumegroup_test.go
  osdsctl/cli/volumesnapshot_test.go
Labels: patch

#380 Add replication controller unit test
  pkg/controller/controller_test.go
  pkg/controller/dr/drcontroller_test.go
Labels: test

#379 Add replication api unit test
  pkg/api/replication.go
  pkg/api/replication_test.go
  pkg/api/router.go
Labels: test

#386 Modify extend volume api
  client/volume.go
  client/volume_test.go
  osdsctl/cli/volume.go
  pkg/api/router.go
  pkg/api/volume.go
  pkg/api/volume_test.go
  pkg/model/volume.go
  test/e2e/e2e_test.go
  test/integration/client_test.go
Labels: patch

#388 Fixed some bugs about host based repliation
  pkg/controller/dr/drcontroller.go
Labels: patch

#389 Update readthedocs website
  docs/readthedocs/community/tsc.md
  docs/readthedocs/index.rst
  docs/readthedocs/installation/How-to-Run-Containerized-OpenSDS-for-Testing-Work.md
  docs/readthedocs/installation/Local-Cluster-Installation-through-Ansible.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-Ceph.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-Cinder-Standalone.md
  docs/readthedocs/installation/Local-Cluster-Installation-with-LVM.md
  docs/readthedocs/installation/Local-Cluster-Installation.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-CSI.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-Flexvolume.md
  docs/readthedocs/installation/OpenSDS-Integration-with-Kubernetes-Service-Catalog.md
  docs/readthedocs/introduction/design-specs.md
  docs/readthedocs/introduction/nbp.md
  docs/readthedocs/introduction/opensds-installer.md
  docs/readthedocs/introduction/opensds.md
Labels: document

#360 Cinder compatible API
  client/profile.go
  contrib/cindercompatibleapi/README.md
  contrib/cindercompatibleapi/api/api_test.go
  contrib/cindercompatibleapi/api/apiversion.go
  contrib/cindercompatibleapi/api/apiversion_test.go
  contrib/cindercompatibleapi/api/attachment.go
  contrib/cindercompatibleapi/api/attachment_test.go
  contrib/cindercompatibleapi/api/router.go
  contrib/cindercompatibleapi/api/snapshot.go
  contrib/cindercompatibleapi/api/snapshot_test.go
  contrib/cindercompatibleapi/api/volume.go
  contrib/cindercompatibleapi/api/volume_test.go
  contrib/cindercompatibleapi/api/volumetype.go
  contrib/cindercompatibleapi/api/volumetype_test.go
  contrib/cindercompatibleapi/cindercompatibleapi.go
  contrib/cindercompatibleapi/converter/apiversion.go
  contrib/cindercompatibleapi/converter/attachment.go
  contrib/cindercompatibleapi/converter/snapshot.go
  contrib/cindercompatibleapi/converter/volume.go
  contrib/cindercompatibleapi/converter/volumetype.go
  pkg/db/drivers/etcd/etcd.go
Labels: feature

#384 volume attach by FC protocol
  contrib/drivers/huawei/dorado/client.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/dorado/model.go
  osdsctl/cli/volumeattachment.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/proto/dock.pb.go
  pkg/dock/proto/dock.proto
  pkg/model/volume.go
Labels: feature

#391 mod the API definition of Extend Volume
  openapi-spec/swagger.yaml
Labels: document

#396 Modify some build error
  dashboard/src/app/business/block/create-volume/create-volume.component.ts
  dashboard/src/app/business/block/volume-detail/snapshot-list/snapshot-list.component.html
  dashboard/src/app/business/block/volumeGroup.component.ts
  dashboard/src/app/business/block/volumeGroup.html
  dashboard/src/app/business/block/volumeList.component.ts
  dashboard/src/app/business/cloud/registry/registry.component.ts
  dashboard/src/app/business/profile/createProfile/createProfile.component.ts
  dashboard/src/app/business/profile/profileCard/profile-card.component.html
Labels: patch

#400 Fixed some bugs abount cinder
  contrib/drivers/openstack/cinder/cinder.go
Labels: patch

#403 delete select obj by tenantID in etcd/etcd.go, etcd itself has this f…
  pkg/db/drivers/etcd/etcd.go
Labels: patch

#395 Remove all ansible scripts
  contrib/ansible/README.md
  contrib/ansible/clean.yml
  contrib/ansible/group_vars/ceph/all.yml
  contrib/ansible/group_vars/ceph/ceph.hosts
  contrib/ansible/group_vars/ceph/ceph.yaml
  contrib/ansible/group_vars/ceph/osds.yml
  contrib/ansible/group_vars/cinder/cinder.yaml
  contrib/ansible/group_vars/common.yml
  contrib/ansible/group_vars/lvm/lvm.yaml
  contrib/ansible/group_vars/osdsdb.yml
  contrib/ansible/group_vars/osdsdock.yml
  contrib/ansible/group_vars/osdslet.yml
  contrib/ansible/install_ansible.sh
  contrib/ansible/local.hosts
  contrib/ansible/roles/cleaner/tasks/main.yml
  contrib/ansible/roles/common/tasks/main.yml
  contrib/ansible/roles/nbp-installer/scenarios/csi.yml
  contrib/ansible/roles/nbp-installer/scenarios/flexvolume.yml
  contrib/ansible/roles/nbp-installer/tasks/main.yml
  contrib/ansible/roles/osdsdb/scenarios/container.yml
  contrib/ansible/roles/osdsdb/scenarios/etcd.yml
  contrib/ansible/roles/osdsdb/tasks/main.yml
  contrib/ansible/roles/osdsdock/scenarios/ceph.yml
  contrib/ansible/roles/osdsdock/scenarios/cinder.yml
  contrib/ansible/roles/osdsdock/scenarios/cinder_standalone.yml
  contrib/ansible/roles/osdsdock/scenarios/lvm.yml
  contrib/ansible/roles/osdsdock/tasks/main.yml
  contrib/ansible/roles/osdslet/tasks/main.yml
  contrib/ansible/site.yml
Labels: duplicate

#409 Scheduler echancement: If the key is prefixed with a colon, then this key is not used to filter the pool
  pkg/controller/selector/filter.go
  pkg/controller/selector/filter_test.go
Labels: patch

#419 Remove package get steps and add protoc cmd
  Makefile
Labels: patch

#425 replication,drbd: initial version
  contrib/drivers/drbd/consts.go
  contrib/drivers/drbd/replication.go
  examples/driver/drbd.yaml
  glide.yaml
  vendor/github.com/LINBIT/godrbdutils/LICENSE
  vendor/github.com/LINBIT/godrbdutils/README.md
  vendor/github.com/LINBIT/godrbdutils/action_string.go
  vendor/github.com/LINBIT/godrbdutils/cmd_string.go
  vendor/github.com/LINBIT/godrbdutils/drbdutils.go
  vendor/github.com/LINBIT/godrbdutils/numbers.go
  vendor/github.com/LINBIT/godrbdutils/resource.go
Labels: feature

#407 attach and detach volume by fc protocol
  contrib/connector/fc/fc.go
  contrib/connector/fc/fibreChannel.go
  contrib/connector/fc/linuxfc.go
  contrib/drivers/huawei/dorado/dorado.go
  pkg/dock/dock.go
Labels: feature

#429 Fix dashboard
  dashboard/package.json
  dashboard/src/app/business/block/create-volume/create-volume.component.html
  dashboard/src/app/business/block/create-volume/replication-group/replication-group.component.html
  dashboard/src/app/business/block/create-volume/replication-group/replication-group.component.ts
  dashboard/src/app/business/block/volume-detail/snapshot-list/snapshot-list.component.html
  dashboard/src/app/business/block/volumeList.component.ts
  dashboard/src/app/business/block/volumeList.html
  dashboard/src/app/business/home/home.component.html
  dashboard/src/app/business/profile/createProfile/createProfile.component.html
  dashboard/src/app/business/profile/createProfile/createProfile.component.ts
  dashboard/src/app/business/profile/createProfile/createProfile.module.ts
  dashboard/src/app/business/profile/profile.component.html
  dashboard/src/app/business/profile/profileCard/profile-card.component.html
  dashboard/src/app/business/profile/profileCard/suspension-frame/suspension-frame.component.html
  dashboard/src/app/business/profile/profileCard/suspension-frame/suspension-frame.component.ts
  dashboard/src/app/business/resource/region/region.component.ts
  dashboard/src/app/i18n/en/keyID.json
  dashboard/src/app/i18n/zh/keyID.json
  dashboard/src/assets/business/css/site.scss
Labels: patch

#430 Fixed some bugs about db,lvm,and makefile.
  Makefile
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/targets/targets.go
  pkg/db/drivers/etcd/etcd.go
Labels: patch
