Repository sodafoundation/api, pull requests merged in 2019-05, with the labels that each got.

#702 Issue 693：CANNOT get profile data when creating sanpshot
  client/volume_test.go
  osdsctl/cli/volume.go
  pkg/api/controllers/volume.go
  pkg/api/controllers/volume_test.go
  pkg/controller/controller.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  testutils/collection/data.go
Labels: patch

#639 Volume multi-attach
  contrib/drivers/ceph/ceph.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/dorado/testdata/dorado.yaml
  contrib/drivers/huawei/fusionstorage/fusionstorage.go
  contrib/drivers/huawei/fusionstorage/fusionstorage_test.go
  contrib/drivers/huawei/fusionstorage/testdata/fusionstorage.yaml
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/lvm_test.go
  contrib/drivers/lvm/targets/nvmeof.go
  contrib/drivers/lvm/testdata/lvm.yaml
  contrib/drivers/openstack/cinder/cinder.go
  contrib/drivers/utils/config/config.go
  contrib/drivers/utils/config/config_test.go
  contrib/drivers/utils/config/testdata/config.yaml
  openapi-spec/swagger.yaml
  osdsctl/cli/pool.go
  osdsctl/cli/volume.go
  osdsctl/cli/volumeattachment.go
  pkg/api/controllers/volume.go
  pkg/api/util/db.go
  pkg/api/util/db_test.go
  pkg/controller/controller.go
  pkg/controller/selector/filter.go
  pkg/controller/selector/filter_test.go
  pkg/controller/selector/selector.go
  pkg/controller/volume/volumecontroller.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/discovery/discovery.go
  pkg/dock/dock.go
  pkg/model/pool.go
  pkg/model/status.go
  pkg/model/volume.go
  script/devsds/lib/lvm.sh
  test/e2e/e2e_test.go
  test/e2e/e2ef_test.go
  testutils/collection/data.go
Labels: feature

#714 Fixed json marshal HTML escape error
  osdsctl/cli/table.go
Labels: patch

#643 Enable DNS resolution of OpenSDS services
  .travis.yml
  Makefile
  cmd/osdsdock/osdsdock.go
  cmd/osdslet/osdslet.go
  examples/opensds.conf
  install/CI/coverage
  install/CI/test
  install/devsds/bootstrap.sh
  install/devsds/install.sh
  install/devsds/lib/ceph.sh
  install/devsds/lib/certificate.sh
  install/devsds/lib/etcd.sh
  install/devsds/lib/keystone.policy.json
  install/devsds/lib/keystone.sh
  install/devsds/lib/lvm.sh
  install/devsds/lib/opensds.sh
  install/devsds/lib/openssl.cnf
  install/devsds/lib/util.sh
  install/devsds/local.conf
  install/devsds/sdsrc
  install/devsds/tools/outfilter.py
  install/devsds/uninstall.sh
  install/kubernetes/README.md
  install/kubernetes/istio-networking/destination-rule-all.yaml
  install/kubernetes/istio-networking/opensds-gateway.yaml
  install/kubernetes/istio-networking/virtual-service-all.yaml
  install/kubernetes/opensds-all.yaml
  install/kubernetes/opensds-apiserver-v1.yaml
  install/kubernetes/opensds-apiserver-v1beta.yaml
  install/kubernetes/opensds-controller-v1.yaml
  install/kubernetes/opensds-external.yaml
  install/kubernetes/opensds-internal.yaml
  install/opensds-authchecker/Dockerfile
  install/opensds-authchecker/entrypoint.sh
  install/opensds-authchecker/keystone.sh
  install/tools/pwdEncrypter/README.md
  install/tools/pwdEncrypter/passwordencrypter.go
  install/tools/pwdEncrypter/pwdEncrypter.yaml
  pkg/db/db.go
  pkg/utils/constants/constants.go
  test/integration/prepare.sh
Labels: feature

#700 Add file share support in profile and model for file share
  client/profile_test.go
  install/devsds/lib/opensds.sh
  pkg/api/controllers/fileshare.go
  pkg/api/controllers/profile.go
  pkg/api/controllers/profile_test.go
  pkg/model/base.go
  pkg/model/fileshareproto/model.pb.go
  pkg/model/fileshareproto/model.proto
  pkg/model/fileshareproto/response.go
  pkg/model/profile.go
  pkg/utils/constants/constants.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  test/e2e/e2ef_test.go
  test/integration/client_test.go
  testutils/collection/data.go
Labels: feature

#717 Set containerized keystone deployment by default
  .travis.yml
  install/devsds/local.conf
  install/kubernetes/opensds-all.yaml
  install/kubernetes/opensds-external.yaml
Labels: patch

#708 Telemetry: Refactor GET API based on the metric spec
  pkg/api/routers/metric.go
  pkg/controller/controller.go
  pkg/controller/metrics/metricscontroller.go
Labels: feature

#709 Telemetry: Changes to metric spec and enhancements to lvm exporter
  contrib/drivers/lvm/lvm_metrics.go
  pkg/controller/metrics/exporters/lvm_exporter/lvm_exporter.go
  pkg/controller/metrics/exporters/lvm_exporter/resources.yaml
  pkg/model/metric.go
Labels: patch

#718 Use goimports to format code automatically
  Makefile
  cmd/osdsdock/osdsdock.go
  cmd/osdslet/osdslet.go
  contrib/connector/nvmeof/nvmeof_helper.go
  contrib/drivers/ceph/ceph.go
  contrib/drivers/drivers.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/fusionstorage/fusionstorage.go
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/metrics_cli.go
  contrib/drivers/lvm/targets/targets.go
  contrib/drivers/openstack/cinder/cinder.go
  osdsctl/cli/table.go
  pkg/api/controllers/fileshare.go
  pkg/api/controllers/metrics.go
  pkg/api/controllers/profile.go
  pkg/api/controllers/volume.go
  pkg/api/util/db.go
  pkg/controller/dr/drcontroller.go
  pkg/controller/metrics/adapters/metrics_sender_to_kafka.go
  pkg/controller/metrics/adapters/metrics_sender_to_prometheus.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/discovery/discovery.go
  pkg/model/fileshareproto/model.pb.go
  pkg/model/proto/model.pb.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: patch

#705 Upload and Download of Prometheus configuration file
  pkg/api/controllers/metrics.go
  pkg/api/routers/metric.go
Labels: patch

#721 Improve osdsctl output message
  osdsctl/cli/dock.go
  osdsctl/cli/pool.go
  osdsctl/cli/profile.go
  osdsctl/cli/replication.go
  osdsctl/cli/volume.go
  osdsctl/cli/volumeattachment.go
  osdsctl/cli/volumegroup.go
  osdsctl/cli/volumesnapshot.go
Labels: patch

#727 Telemetry:Metric Driver mock test (UT)
  contrib/drivers/lvm/lvm_metrics_test.go
Labels: patch

#733 Shrink size of hotpot binary files
  Makefile
Labels: patch

#726 Add dock and controller for file share
  contrib/drivers/filesharedrivers/drivers.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  contrib/drivers/utils/config/constants.go
  examples/driver/nfs.yaml
  install/devsds/lib/opensds.sh
  pkg/api/controllers/fileshare.go
  pkg/api/controllers/profile.go
  pkg/controller/client/client.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/fileshare/filesharecontroller.go
  pkg/controller/selector/selector.go
  pkg/controller/volume/volumecontroller_test.go
  pkg/db/db.go
  pkg/dock/client/client.go
  pkg/dock/dock.go
  pkg/model/base.go
  pkg/model/fileshare.go
  pkg/model/fileshareproto/model.pb.go
  pkg/model/fileshareproto/model.proto
  pkg/model/fileshareproto/response.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  pkg/utils/config/config_define.go
  testutils/controller/testing/client.go
  testutils/driver/sample.go
Labels: feature

#728 POST API to collect metrics and send to registered adapters
  contrib/drivers/drivers.go
  contrib/drivers/lvm/lvm_metrics_test.go
  contrib/drivers/lvm/metrics_cli.go
  pkg/api/controllers/fileshare.go
  pkg/api/controllers/metrics.go
  pkg/api/routers/metrics.go
  pkg/controller/controller.go
  pkg/controller/metrics/metrics_controller.go
  pkg/controller/volume/volumecontroller_test.go
  pkg/dock/dock.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  testutils/controller/testing/client.go
  testutils/dock/testing/client.go
Labels: feature

#738 Fixed printing bug, make the summary info printing more limpid
  install/devsds/install.sh
Labels: patch

#742 Uniform naming access protocol
  contrib/connector/connector.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/fusionstorage/fusionstorage.go
  contrib/drivers/lvm/targets/targets.go
  contrib/drivers/utils/config/constants.go
  examples/driver/fusionstorage.yaml
  pkg/controller/controller.go
Labels: patch

#736 GET API to retrieve Grafana and Alert manager URLs
  cmd/osdslet/osdslet.go
  pkg/api/controllers/metrics.go
  pkg/api/routers/metrics.go
  pkg/controller/controller.go
  pkg/controller/metrics/metrics_controller.go
  pkg/model/metric.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  pkg/utils/config/config_define.go
  testutils/controller/testing/client.go
  testutils/dock/testing/client.go
Labels: patch

#739 Add opensds controller api spec validation
  install/CI/test
  openapi-spec/swagger.yaml
Labels: document

#731 Fusionstorage driver support for Fusionstorage storage device version 8.0
  contrib/connector/iscsi/helper.go
  contrib/drivers/huawei/fusionstorage/constants.go
  contrib/drivers/huawei/fusionstorage/fsclient.go
  contrib/drivers/huawei/fusionstorage/fusionstorage.go
  contrib/drivers/huawei/fusionstorage/fusionstorage_test.go
  contrib/drivers/huawei/fusionstorage/model.go
  contrib/drivers/huawei/fusionstorage/testdata/fusionstorage.yaml
  pkg/controller/controller.go
Labels: patch

#743 create user and endpoint for gelato in the opensdsio/opensds-authchecker image
  install/opensds-authchecker/keystone.sh
Labels: patch

#724 Telemetry: Ceph Metrics Driver Implementation
  contrib/drivers/ceph/ceph_metrics.go
  contrib/drivers/ceph/metrics_cli.go
  contrib/drivers/drivers.go
Labels: feature

#744 Telemetry: Make Driver naming consistent with exporter
  Makefile
  contrib/drivers/lvm/lvm_metrics.go
  contrib/drivers/lvm/lvm_metrics_test.go
  contrib/drivers/lvm/metrics_cli.go
  pkg/controller/metrics/exporters/lvm_exporter/lvm_exporter.go
  pkg/model/metric.go
Labels: patch

#735 Fileshare dock discovery code
  client/pool_test.go
  install/devsds/lib/lvm.sh
  pkg/api/controllers/fileshare.go
  pkg/controller/controller.go
  pkg/controller/fileshare/filesharecontroller.go
  pkg/controller/selector/selector.go
  pkg/controller/selector/selector_test.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/discovery/discovery.go
  pkg/dock/dock.go
  pkg/utils/utils.go
  testutils/collection/data.go
  testutils/db/fake.go
  testutils/db/testing/client.go
Labels: feature

#740 HPE Nimble storage driver
  .gitignore
  contrib/drivers/drivers.go
  contrib/drivers/hpe/nimble/client.go
  contrib/drivers/hpe/nimble/common.go
  contrib/drivers/hpe/nimble/constants.go
  contrib/drivers/hpe/nimble/model.go
  contrib/drivers/hpe/nimble/nimble.go
  contrib/drivers/utils/config/constants.go
  examples/driver/hpe_nimble.yaml
  pkg/utils/config/config_define.go
Labels: feature

#762 Fix osdsdock Discover method
  pkg/dock/discovery/discovery.go
Labels: patch

#761 Add snapshot of fileshare dock and controller methods
  contrib/drivers/filesharedrivers/drivers.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  pkg/api/controllers/fileshare.go
  pkg/controller/controller.go
  pkg/controller/fileshare/filesharecontroller.go
  pkg/controller/volume/volumecontroller_test.go
  pkg/db/db.go
  pkg/dock/dock.go
  pkg/model/fileshare.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  testutils/controller/testing/client.go
  testutils/driver/sample.go
Labels: feature

#768 Fileshare API server mock test cases
  pkg/api/controllers/fileshare_test.go
Labels: patch

#767 Add 3rd party conf support for telemetry
  cmd/osdsapiserver/osdsapiserver.go
  cmd/osdslet/osdslet.go
  pkg/api/controllers/metrics.go
  pkg/controller/metrics/adapters/metrics_sender_to_prometheus.go
  pkg/controller/metrics/metrics_controller.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  pkg/utils/config/config_define.go
Labels: patch

#771 Updated logic to handle metrics labels for NodeExporter and PushGateway
  cmd/osdslet/osdslet.go
  pkg/controller/metrics/adapters/metrics_sender_to_prometheus.go
  pkg/utils/config/config_define.go
Labels: patch

#772 dock and controller logic. After formatting
  contrib/drivers/filesharedrivers/drivers.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  pkg/api/controllers/fileshare.go
  pkg/controller/controller.go
  pkg/controller/fileshare/filesharecontroller.go
  pkg/controller/volume/volumecontroller_test.go
  pkg/dock/dock.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  testutils/controller/testing/client.go
  testutils/dock/testing/client.go
  testutils/driver/sample.go
Labels: feature

#775 Add authorization support for Telemetry APIs
  examples/policy.json
  pkg/api/controllers/metrics.go
Labels: patch

#776 Optimize the magic number
  contrib/drivers/huawei/dorado/client.go
  contrib/drivers/huawei/dorado/constants.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/dorado/replication.go
Labels: patch

#778 Add output content type
  pkg/api/controllers/base.go
Labels: patch

#777 Add Kafka conf. and send MetricSpec JSON on topic
  cmd/osdslet/osdslet.go
  pkg/controller/metrics/adapters/metrics_sender_to_kafka.go
  pkg/utils/config/config_define.go
Labels: patch

#764 Telemetry: Metric collection from all resources
  client/pool_test.go
  contrib/drivers/ceph/ceph_metrics.go
  contrib/drivers/drivers.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  contrib/drivers/hpe/nimble/nimble.go
  contrib/drivers/huawei/fusionstorage/fusionstorage.go
  contrib/drivers/lvm/lvm_metrics.go
  contrib/drivers/lvm/lvm_metrics_test.go
  contrib/drivers/lvm/metrics_cli.go
  pkg/api/controllers/metrics.go
  pkg/api/routers/fileshare.go
  pkg/controller/controller.go
  pkg/controller/metrics/exporters/lvm_exporter/lvm_exporter.go
  pkg/controller/metrics/exporters/lvm_exporter/resources.yaml
  pkg/dock/discovery/discovery.go
  pkg/dock/dock.go
  pkg/model/metric.go
  testutils/collection/data.go
Labels: feature

#781 Fix panic error in CI log
  install/CI/coverage
  pkg/api/controllers/fileshare_test.go
  pkg/api/controllers/volume_test.go
Labels: patch

#774 Creation of sample pool and volume group for fileshare
  contrib/drivers/filesharedrivers/nfs/cli.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  contrib/drivers/utils/config/constants.go
  install/devsds/install.sh
  install/devsds/lib/lvm.sh
  install/devsds/lib/opensds.sh
  install/devsds/local.conf
  pkg/api/controllers/fileshare.go
  pkg/controller/controller.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/discovery/discovery_test.go
  pkg/model/fileshare.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  testutils/collection/data.go
Labels: patch

#782 modifed the drbd yaml config file default path
  contrib/drivers/drbd/consts.go
Labels: patch

#783 Telemtry: Bug fix #773
  contrib/drivers/lvm/metrics_cli.go
Labels: patch

#785 Fix issue and add poolId
  contrib/drivers/filesharedrivers/nfs/nfs.go
  pkg/db/drivers/etcd/etcd.go
Labels: patch

#784 Update e2e test flow
  .gitignore
  test/e2e/e2e_test.go
  test/e2e/e2ef_test.go
Labels: patch

#793 fix #788 and #789
  pkg/controller/metrics/adapters/metrics_sender_to_prometheus.go
Labels: patch

#795 File share profile test cases
  pkg/api/controllers/profile_test.go
  testutils/collection/data.go
Labels: patch

#791 Telemetry: Fix for #787
  contrib/drivers/lvm/lvm_metrics.go
  contrib/drivers/lvm/lvm_metrics_test.go
  contrib/drivers/lvm/metrics_cli.go
Labels: patch

#792 Add fileshare controller unit test cases for create/delete fileshare and create/delete filesharesnapshots
  pkg/controller/fileshare/filesharecontroller_test.go
  testutils/collection/data.go
Labels: patch

#716 file share cli
  client/client.go
  client/fake.go
  client/fileshare.go
  client/fileshare_test.go
  osdsctl/cli/cli.go
  osdsctl/cli/fileshare.go
  osdsctl/cli/fileshare_test.go
  osdsctl/cli/fileshareacl.go
  osdsctl/cli/fileshareacl_test.go
  osdsctl/cli/filesharesnapshot.go
  osdsctl/cli/filesharesnapshot_test.go
  testutils/collection/data.go
Labels: feature

#794 Adding profile to CreateFileShareAcl and snapshot issue
  contrib/drivers/filesharedrivers/drivers.go
  contrib/drivers/filesharedrivers/nfs/cli.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  pkg/api/controllers/fileshare.go
  pkg/api/util/db.go
  pkg/controller/controller.go
  pkg/controller/fileshare/filesharecontroller.go
  pkg/controller/fileshare/filesharecontroller_test.go
  pkg/controller/volume/volumecontroller_test.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/dock.go
  pkg/model/fileshare.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  testutils/controller/testing/client.go
  testutils/driver/sample.go
Labels: patch

#796 Add keystone to fileshare
  examples/policy.json
  pkg/api/controllers/fileshare.go
Labels: patch

#797 Move exporters under contrib folder
  .travis.yml
  Makefile
  README.md
  contrib/drivers/lvm/lvm_metrics.go
  contrib/drivers/lvm/lvm_metrics_test.go
  contrib/drivers/lvm/metrics_cli.go
  contrib/exporters/lvm_exporter/lvm_exporter.go
  install/CI/coverage
  install/CI/test
  pkg/db/drivers/etcd/etcd.go
Labels: patch

#801 Patch 799 - Create file share fails because of no availability pool
  examples/driver/nfs.yaml
  install/devsds/lib/lvm.sh
Labels: patch
