Repository sodafoundation/api, pull requests merged in 2019-06, with the labels that each got.

#682 Oceanstor file driver
  contrib/drivers/filesharedrivers/drivers.go
  contrib/drivers/filesharedrivers/oceanstor/cifs.go
  contrib/drivers/filesharedrivers/oceanstor/constants.go
  contrib/drivers/filesharedrivers/oceanstor/model.go
  contrib/drivers/filesharedrivers/oceanstor/nfs.go
  contrib/drivers/filesharedrivers/oceanstor/oceanclient.go
  contrib/drivers/filesharedrivers/oceanstor/oceanstor.go
  contrib/drivers/filesharedrivers/oceanstor/testdata/oceanstor.yaml
  contrib/drivers/filesharedrivers/oceanstor/util.go
  contrib/drivers/filesharedrivers/oceanstor/util_test.go
  contrib/drivers/utils/config/constants.go
  pkg/controller/controller.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/discovery/discovery.go
  pkg/utils/config/config_define.go
Labels: feature

#807 add protoc version precheck
  Makefile
Labels: patch

#808 Update protoc version to v3.8.0
  pkg/model/proto/model.pb.go
Labels: patch

#809 Make docker image tag configurable
  Makefile
Labels: patch

#813 Add fileshare e2e test cases
  test/e2e/e2e_test.go
Labels: patch

#815 Add multi-attach feature for lvm driver
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/targets/iscsi.go
  contrib/drivers/lvm/targets/nvmeof.go
  contrib/drivers/lvm/targets/targets.go
Labels: patch

#825 Fix for issue#812
  pkg/db/drivers/etcd/etcd.go
Labels: patch

#826 Telemetry : Fix for https://github.com/opensds/opensds/issues/800
  cmd/osdslet/osdslet.go
  pkg/utils/config/config_define.go
Labels: patch

#827 Reverting the code to support fileshare access
  contrib/drivers/filesharedrivers/nfs/nfs.go
Labels: patch

#829 Update the layout of codecov
  codecov.yml
Labels: patch

#819 manila driver
  Gopkg.lock
  Gopkg.toml
  contrib/drivers/filesharedrivers/drivers.go
  contrib/drivers/filesharedrivers/manila/manila.go
  contrib/drivers/openstack/cinder/cinder.go
  contrib/drivers/utils/config/constants.go
  examples/driver/manila.yaml
  osdsctl/cli/fileshareacl.go
  pkg/api/controllers/fileshare.go
  pkg/controller/controller.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/db/drivers/etcd/etcd_test.go
  pkg/dock/discovery/discovery.go
  pkg/utils/config/config_define.go
  testutils/db/fake.go
  testutils/db/testing/client.go
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/auth_result.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/schedulerstats/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/noauth/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/noauth/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/endpoint_location.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/utils/base_endpoint.go
  vendor/github.com/gophercloud/gophercloud/pagination/pager.go
  vendor/github.com/gophercloud/gophercloud/params.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/results.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
Labels: feature

#838 Telemetry: Ceph volume metrics with updated Ceph Metrics drivers' unit test case
  contrib/drivers/ceph/ceph_metrics.go
  contrib/drivers/ceph/ceph_metrics_test.go
  contrib/drivers/ceph/metrics_cli.go
Labels: patch

#769 Add Fileshare Api Specs in swagger
  openapi-spec/swagger.yaml
Labels: document

#840 Telemetry Fix for issue https://github.com/opensds/opensds/issues/830
  pkg/controller/metrics/metrics_controller.go
Labels: patch

#843 nvme over diverse fabric supoort & nbp nvme-tcp support
  contrib/connector/nvmeof/nvmeof_helper.go
  contrib/drivers/lvm/targets/nvmeof.go
  contrib/drivers/lvm/targets/targets.go
  install/devsds/lib/lvm.sh
  test/e2e/e2ef_test.go
Labels: patch

#842 Fix issue #841 and #822
  contrib/connector/nvmeof/nvmeof_helper.go
  contrib/drivers/filesharedrivers/drivers.go
  contrib/drivers/filesharedrivers/manila/manila.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  contrib/drivers/filesharedrivers/oceanstor/oceanstor.go
  contrib/drivers/huawei/dorado/metrics.go
  contrib/drivers/lvm/targets/nvmeof.go
  pkg/api/controllers/fileshare.go
  pkg/controller/controller.go
  pkg/controller/fileshare/filesharecontroller.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/dock.go
  pkg/model/proto/model.pb.go
  testutils/driver/sample.go
Labels: patch

#844 Merge development into master branch to publish Capri RC-02
  contrib/connector/nvmeof/nvmeof_helper.go
  contrib/drivers/filesharedrivers/drivers.go
  contrib/drivers/filesharedrivers/manila/manila.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  contrib/drivers/filesharedrivers/oceanstor/oceanstor.go
  contrib/drivers/huawei/dorado/metrics.go
  contrib/drivers/lvm/targets/nvmeof.go
  contrib/drivers/lvm/targets/targets.go
  install/devsds/lib/lvm.sh
  pkg/api/controllers/fileshare.go
  pkg/controller/controller.go
  pkg/controller/fileshare/filesharecontroller.go
  pkg/db/drivers/etcd/etcd.go
  pkg/dock/dock.go
  pkg/model/proto/model.pb.go
  test/e2e/e2ef_test.go
  testutils/driver/sample.go
Labels: patch, release

#845 Update the cli command of FileShareAcl
  osdsctl/cli/fileshareacl.go
Labels: patch

#850 Telemetry: Fix for https://github.com/opensds/opensds/issues/847
  pkg/controller/metrics/metrics_controller.go
Labels: patch

#848 Telemtery: Fix for https://github.com/opensds/opensds/issues/846
  contrib/exporters/lvm_exporter/lvm_exporter.go
Labels: patch

#849 Fix for issue#832 and some validation
  pkg/api/util/db.go
Labels: patch

#858 get profile derived from volume
  pkg/api/controllers/volume.go
Labels: patch

#859 print http status info when got an empty body
  osdsctl/cli/common.go
Labels: patch

#855 fix for #811 and some validation
  pkg/api/controllers/fileshare.go
  pkg/api/util/db.go
  pkg/controller/controller.go
Labels: patch

#860 Ignore patch status of codecov
  codecov.yml
Labels: patch

#852 hotpot connector for NFS
  contrib/connector/common.go
  contrib/connector/connector.go
  contrib/connector/nfs/helper.go
  contrib/connector/nfs/nfs.go
  contrib/drivers/utils/config/constants.go
  pkg/dock/dock.go
Labels: patch

#865 Telemetry: Fix for https://github.com/opensds/opensds/issues/864 and https://github.com/opensds/opensds/issues/706
  pkg/model/metric.go
  pkg/utils/config/config_define.go
Labels: patch

#857 Fix some bugs and improve log record
  pkg/api/controllers/fileshare.go
  pkg/api/controllers/metrics.go
  pkg/api/controllers/profile.go
  pkg/api/controllers/replication.go
  pkg/api/controllers/volume.go
  pkg/api/controllers/volumeGroup.go
  pkg/api/util/db.go
  pkg/api/util/db_test.go
  pkg/controller/controller.go
  pkg/dock/discovery/discovery.go
  pkg/model/status.go
  test/e2e/e2ef_test.go
Labels: patch

#862 make the profile name unique with the same storage type
  pkg/db/drivers/etcd/etcd.go
Labels: patch

#867 Fix issue #866 caused by #855
  pkg/api/controllers/fileshare.go
Labels: patch

#856 Fix for #729 - Removed Pre-defined profile properties
  pkg/api/controllers/profile.go
Labels: patch

#876 Telemetry : Fix for issue #873
  contrib/drivers/lvm/lvm_metrics.go
  contrib/drivers/lvm/lvm_metrics_test.go
  contrib/drivers/lvm/metrics_cli.go
Labels: patch

#877 Fix bugs relate on oceanstor file share driver
  contrib/drivers/filesharedrivers/nfs/nfs.go
  contrib/drivers/filesharedrivers/oceanstor/constants.go
  contrib/drivers/filesharedrivers/oceanstor/oceanstor.go
Labels: patch

#881 Fix #790 - Remove the host information update from db.
  pkg/db/drivers/etcd/etcd.go
  pkg/db/drivers/etcd/etcd_test.go
Labels: patch

#883 Add accessprotocol to default profile for fileshare
  install/devsds/lib/opensds.sh
  pkg/api/controllers/profile.go
Labels: patch

#889 Adding nfs-kernel installation
  install/devsds/lib/lvm.sh
  install/devsds/lib/opensds.sh
Labels: patch

#891 When creating fileshare, the request parameter should have no "exportLocations"
  osdsctl/cli/fileshare.go
Labels: patch

#890 Add scutech cms driver
  contrib/drivers/replication_drivers.go
  contrib/drivers/scutech/cms/replication.go
  contrib/drivers/scutech/cms/scmstask.go
  contrib/drivers/scutech/cms/scmsutils.go
  contrib/drivers/utils/config/constants.go
Labels: CAPRI, feature

#893 Check the parameters of cli according to swagger.yaml
  osdsctl/cli/fileshare.go
  osdsctl/cli/fileshareacl.go
Labels: patch

#896 Telemetry: Typo error in metric name fix for #895
  contrib/exporters/lvm_exporter/lvm_exporter.go
Labels: patch

#903 Telemetry : Fix for #902
  pkg/controller/controller.go
  pkg/controller/metrics/metrics_controller.go
  pkg/model/metric.go
Labels: patch

#901 Solve some fileshare problems
  contrib/drivers/filesharedrivers/manila/manila.go
  osdsctl/cli/fileshare.go
  osdsctl/cli/fileshare_test.go
  osdsctl/cli/fileshareacl.go
  osdsctl/cli/filesharesnapshot.go
  pkg/api/controllers/fileshare.go
  pkg/db/drivers/etcd/etcd.go
Labels: patch

#904 Fix for snapshot empty name validation
  contrib/drivers/filesharedrivers/nfs/cli.go
  contrib/drivers/filesharedrivers/nfs/nfs.go
  pkg/api/controllers/fileshare.go
  pkg/api/util/db.go
Labels: patch

#908 Modify the description of the cli command help
  osdsctl/cli/filesharesnapshot.go
Labels: patch

#909 Improve the log msg
  pkg/controller/controller.go
  pkg/dock/dock.go
Labels: patch

#912 Solve some volume group update and delete errors.
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/targets/iscsi.go
  pkg/api/controllers/volumeGroup.go
  pkg/api/util/db.go
  pkg/controller/controller.go
  pkg/dock/dock.go
  test/e2e/e2ef_test.go
Labels: patch

#919 Fixed rbd hosts type issue
  contrib/connector/rbd/rbd.go
Labels: CAPRI, patch

#920 Merge development into master branch
  contrib/connector/rbd/rbd.go
Labels: CAPRI
