Repository sodafoundation/api, pull requests merged in 2019-03, with the labels that each got.

#617 add voume extend auto-completion functionality
  osdsctl/completion/osdsctl.bash_completion
Labels: patch

#619 Set default GOPATH to golang's default
  script/devsds/bootstrap.sh
Labels: patch

#627 add unit test and fix some bugs
  contrib/drivers/huawei/fusionstorage/constants.go
  contrib/drivers/huawei/fusionstorage/dsware.go
  contrib/drivers/huawei/fusionstorage/dsware_test.go
  contrib/drivers/huawei/fusionstorage/fsclient.go
  contrib/drivers/huawei/fusionstorage/testdata/fusionstorage.yaml
  pkg/utils/exec/exec.go
Labels: patch

#628 Test the configuration file only to make unit test execution faster.
  contrib/drivers/huawei/fusionstorage/dsware_test.go
Labels: patch

#629 Fix some issues related to the fusionstorage iscsi mapping.
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/fusionstorage/fsclient.go
  contrib/drivers/huawei/fusionstorage/fusionstorage.go
  contrib/drivers/huawei/fusionstorage/fusionstorage_test.go
  contrib/drivers/openstack/cinder/cinder.go
Labels: patch

#630 Add some test cases in client package
  client/client.go
  client/client_test.go
  client/receiver.go
  client/replication_test.go
  client/volume_test.go
Labels: patch

#634 Change the projectId to tenantId in swagger
  openapi-spec/swagger.yaml
Labels: document

#635 Run go fmt to update the code
  pkg/controller/controller_test.go
Labels: patch

#632 contrib: add NVMeoF support
  contrib/connector/connector.go
  contrib/connector/nvmeof/nvmeof.go
  contrib/connector/nvmeof/nvmeof_helper.go
  contrib/drivers/lvm/lvm.go
  contrib/drivers/lvm/targets/nvmeof.go
  contrib/drivers/lvm/targets/targets.go
  pkg/controller/controller.go
  script/devsds/lib/lvm.sh
  test/e2e/connector/connector.go
  test/e2e/e2ef_test.go
Labels: feature
