Repository sodafoundation/api, pull requests merged in 2019-04, with the labels that each got.

#637 use a keystone installed in a container
  script/devsds/install.sh
  script/devsds/lib/keystone.sh
  script/devsds/lib/opensds.sh
  script/devsds/local.conf
Labels: patch

#640 modifed the driver name to be same as definition in code
  examples/opensds.conf
Labels: patch

#644 add keystone policy
  script/devsds/lib/keystone.policy.json
  script/devsds/lib/keystone.sh
Labels: patch

#645 Fix multi-lun in the lun group deleting bug
  contrib/drivers/huawei/dorado/client.go
  contrib/drivers/huawei/dorado/dorado.go
  contrib/drivers/huawei/dorado/model.go
Labels: patch

#648 Fixed some bugs about profile
  osdsctl/cli/profile.go
  pkg/api/volume.go
  pkg/controller/controller.go
  pkg/controller/selector/selector.go
  pkg/model/profile.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
Labels: patch

#650 Fixed cann't delete volume without binding pool bug
  pkg/api/db.go
  pkg/api/volume.go
  pkg/controller/controller.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
Labels: patch

#651 Fixed dorado terminating connection bugs
  contrib/drivers/huawei/dorado/client.go
  contrib/drivers/huawei/dorado/dorado.go
Labels: patch

#647 Use the new opensds-authchecker image
  script/devsds/install.sh
  script/devsds/lib/keystone.sh
  script/devsds/lib/opensds.sh
  script/devsds/local.conf
Labels: patch

#652 Add some sub-test methods
  client/client_test.go
  client/receiver.go
  pkg/api/db_test.go
  pkg/api/dock_test.go
  pkg/api/pool_test.go
  pkg/api/profile_test.go
  pkg/api/version_test.go
  pkg/utils/urls/urls_test.go
  testutils/collection/data.go
Labels: patch

#656 minor spell fix in install sub headers
  docs/readthedocs/installation/Local-Cluster-Installation.md
Labels: document

#661 bug: fix the umout issue
  script/devsds/lib/lvm.sh
Labels: patch

#663 bug: fix the issue about target creation failure
  contrib/drivers/lvm/targets/nvmeof.go
Labels: patch

#664 Hotpot service dockerfile update
  cmd/osdsapiserver/Dockerfile
  cmd/osdsdock/Dockerfile
  cmd/osdslet/Dockerfile
  docker-compose.yml
  docs/readthedocs/installation/Local-Cluster-Installation.md
  script/devsds/local.conf
Labels: patch

#665 Update some test cases in api package
  pkg/api/profile_test.go
  pkg/api/replication.go
  pkg/api/replication_test.go
  pkg/api/volumeGroup_test.go
  pkg/api/volume_test.go
  testutils/collection/data.go
Labels: patch

#666 Update README.md file in client package
  client/README.md
Labels: document

#669 Update some method handles in apiserver
  pkg/api/filter/auth/auth.go
  pkg/api/filter/auth/keystone.go
  pkg/api/policy/policy.go
  pkg/api/replication.go
  pkg/context/context.go
  pkg/model/error.go
  pkg/model/proto/response_test.go
Labels: patch

#670 Fixed keystone container entrypoint get ip issue
  script/opensds-authchecker/entrypoint.sh
Labels: patch

#675 make keystone authentication print info more clearly
  client/auth.go
  client/client.go
  client/receiver.go
  osdsctl/cli/cli.go
  osdsctl/main.go
Labels: patch

#676 Refactor API code to make more modular
  pkg/api/controllers/base.go
  pkg/api/controllers/dock.go
  pkg/api/controllers/dock_test.go
  pkg/api/controllers/pool.go
  pkg/api/controllers/pool_test.go
  pkg/api/controllers/profile.go
  pkg/api/controllers/profile_test.go
  pkg/api/controllers/replication.go
  pkg/api/controllers/replication_test.go
  pkg/api/controllers/version.go
  pkg/api/controllers/version_test.go
  pkg/api/controllers/volume.go
  pkg/api/controllers/volumeGroup.go
  pkg/api/controllers/volumeGroup_test.go
  pkg/api/controllers/volume_test.go
  pkg/api/main.go
  pkg/api/router.go
  pkg/api/routers/block.go
  pkg/api/routers/router.go
  pkg/api/util/db.go
  pkg/api/util/db_test.go
Labels: patch

#677 Fix some errors in devsds
  osdsctl/cli/cli.go
  pkg/api/main.go
  pkg/api/routers/router.go
  script/devsds/lib/keystone.sh
  script/devsds/lib/opensds.sh
  script/devsds/local.conf
Labels: patch

#679 Replace all golang.org/x/net/context with context
  pkg/api/controllers/replication.go
  pkg/api/controllers/volume.go
  pkg/api/controllers/volumeGroup.go
  pkg/api/controllers/volume_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/policy/executor/executordeletesnapshot.go
  pkg/controller/policy/executor/executorintervalsnapshot.go
  pkg/controller/volume/volumecontroller.go
  pkg/controller/volume/volumecontroller_test.go
  pkg/db/drivers/etcd/client.go
  pkg/dock/dock.go
Labels: patch

#681 Update docker-compose.yml file
  docker-compose.yml
Labels: patch

#687 Add file share and snapshot api
  pkg/api/controllers/fileshare.go
  pkg/api/routers/fileshare.go
  pkg/api/util/db.go
  pkg/db/db.go
  pkg/db/drivers/etcd/etcd.go
  pkg/model/fileshare.go
  pkg/model/status.go
  pkg/utils/urls/urls.go
  testutils/collection/data.go
  testutils/db/fake.go
  testutils/db/testing/client.go
Labels: feature

#673 added GET APIs for metrics
  pkg/api/controllers/metrics.go
  pkg/controller/controller.go
  pkg/controller/metrics/adapters/metrics_sender_to_kafka.go
  pkg/controller/metrics/adapters/metrics_sender_to_prometheus.go
  pkg/controller/metrics/metricscontroller.go
  pkg/model/metric.go
  pkg/model/proto/model.pb.go
  pkg/model/proto/model.proto
  testutils/controller/testing/client.go
Labels: feature

#694 POST API to send alerts to Alert manager
  pkg/api/controllers/alert.go
  pkg/api/routers/alert.go
  pkg/model/alert.go
Labels: feature

#698 DELETE fileshare API
  pkg/api/controllers/fileshare.go
Labels: patch

#697 Telemetry: Lvm exporter for Prometheus
  Gopkg.lock
  Gopkg.toml
  contrib/drivers/drivers.go
  contrib/drivers/lvm/lvm_metrics.go
  contrib/drivers/lvm/lvm_metrics_test.go
  contrib/drivers/lvm/metrics_cli.go
  pkg/controller/metrics/exporters/lvm_exporter/lvm_exporter.go
  pkg/controller/metrics/metricscontroller.go
  pkg/model/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
Labels: feature
